# Generated by Django 3.0.8 on 2020-08-14 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='class_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Class'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='classroom_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Classroom'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='course_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Course'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='professor_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='timetableapp.Professor'),
        ),
    ]
