# Generated by Django 3.0.8 on 2020-08-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetableapp', '0003_auto_20200814_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='professor_id',
            field=models.CharField(max_length=2000, primary_key=True, serialize=False),
        ),
    ]
